name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Hello world
      run: echo "Hello world"
    - name: Xcode list
      run: ls /Applications
